name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          path: ./
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          path: ./Admin
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run:  cd ./thebccampaign-admin && npm install
      - name: Build Angular app
        run: |
              cd ./Admin
              npm run build --prod --base-href=/thebccampaign-admin/
              mkdir -p  ./dist/thebccampaign-admin/thebccampaign-admin
              cp -R ./dist/thebccampaign-admin/*.* ./dist/thebccampaign-admin/thebccampaign-admin
         
      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./thebccampaign-admin/Admin/dist/thebccampaign-admin
          enable_jekyll: true
    
