name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          path: ./
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          path: ./Admin
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run:  |
              cd ./Admin/Admin 
              npm install
      - name: Build Admin tool
        run: |
              cp -R ./Admin/Admin/src/app/comments/*.* ./Admin/Widget/src/app/comments/
              cd ./Admin/Admin 
              npm run build --prod --base-href=/thebccampaign-admin/
              mkdir -p  ./dist/thebccampaign-admin/thebccampaign-admin
              cp -R ./dist/thebccampaign-admin/*.* ./dist/thebccampaign-admin/thebccampaign-admin
      - name: Build Widget
        run: |
              cd ./Admin/Widget 
              npm run build --prod --base-href=/thebccampaign/
              
      - name: Push generated webpage to another repository
        uses: nkoppel/push-files-to-another-repository@1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: ./Admin/Widget/dist/thebccampaign/
          destination-username: 'ChrisColeTech'
          destination-repository: 'chriscoletech.github.io'
          destination-directory: 'thebccampaign'
          destination-branch: 'gh-pages'
          commit-email: 'moneymagnet216@gmail.com'
      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Admin/Admin/dist/thebccampaign-admin/
          enable_jekyll: true
    
