name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          path: ./
      - name: copy files
        run: |     
            dir
            cd ./Widget/src/app/comments/
            dir
            cd ../../../..
            dir
            cd ./Admin/src/app/comments/
            dir
            cd ../../../..
            cp -R *.* ./Widget/src/app/comments/
            
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build Admin tool
        run: |              
              cd ./Admin
              npm install
              npm run build --prod --base-href=/thebccampaign-admin/
              mkdir -p  ./dist/thebccampaign-admin/thebccampaign-admin
              cp -R ./dist/thebccampaign-admin/*.* ./dist/thebccampaign-admin/thebccampaign-admin
      - name: Build Widget
        run: |
              cd ./Widget 
              npm install  
              npm run build --prod --base-href=/thebccampaign/
              
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: './Widget/dist/thebccampaign/'
          destination-github-username: 'ChrisColeTech'
          destination-repository-name: 'thebccampaign'
          user-email:  'moneymagnet216@gmail.com'
          target-branch: 'gh-pages'
      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Admin/dist/thebccampaign-admin/
          enable_jekyll: true
    
